apiVersion: v1
kind: ConfigMap
metadata:
  name: reactoracle-grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  reactoracle.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
