from __future__ import annotations

from .models import DurableDataZone, GoldTableContract, PlatformArchitecture, PlatformNode


def build_platform_architecture() -> PlatformArchitecture:
    nodes = [
        PlatformNode(
            id="contoso",
            name="Contoso Forge Lite",
            layer="source",
            state="planned",
            provider=".NET / C#",
            role="Optional deterministic synthetic retail data + causal ML truth",
            durable=False,
            location="Ephemeral generator job",
        ),
        PlatformNode(
            id="github",
            name="GitHub",
            layer="delivery",
            state="external",
            provider="GitHub",
            role="Source, DAGs, manifests, CI/CD and release artifacts",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="motherduck",
            name="MotherDuck / DuckLake",
            layer="lakehouse",
            state="planned",
            provider="MotherDuck",
            role="Durable Parquet lakehouse for Raw, Bronze, Silver, Gold and ML features",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="airflow",
            name="Airflow",
            layer="orchestration",
            state="live",
            provider="Apache Airflow",
            role="Pipeline orchestration and external job coordination",
            durable=False,
            location="Oracle K3s",
        ),
        PlatformNode(
            id="spark",
            name="Spark",
            layer="compute",
            state="live",
            provider="Apache Spark",
            role="Distributed transformations, joins, partitioning and feature engineering",
            durable=False,
            location="Oracle K3s",
        ),
        PlatformNode(
            id="kafka",
            name="Managed Kafka",
            layer="source",
            state="external",
            provider="External free tier",
            role="Streaming source without consuming Oracle VM memory",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="kaggle",
            name="Kaggle + MLJAR",
            layer="ml",
            state="planned",
            provider="Kaggle",
            role="Optional bounded external ML / AutoML execution from feature tables",
            durable=False,
            location="Managed external compute",
        ),
        PlatformNode(
            id="neon",
            name="Neon",
            layer="serving",
            state="optional",
            provider="Neon Postgres",
            role="Compact serving tables, ML metrics, latest predictions and platform metadata",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="dbt",
            name="dbt",
            layer="serving",
            state="planned",
            provider="dbt Core",
            role="Optional analytical marts over durable Gold data",
            durable=False,
            location="Ephemeral Oracle K3s job",
        ),
        PlatformNode(
            id="bi",
            name="BI / SQL consumers",
            layer="consumption",
            state="planned",
            provider="Power BI / SQL",
            role="Consume published Gold tables; business React applications are out of scope",
            durable=False,
            location="External clients",
        ),
        PlatformNode(
            id="grafana",
            name="Grafana stack",
            layer="observability",
            state="live",
            provider="Grafana / Prometheus / Loki",
            role="Operational metrics and logs",
            durable=False,
            location="Oracle K3s",
        ),
        PlatformNode(
            id="reactoracle",
            name="ReactOracle",
            layer="control",
            state="live",
            provider="React + Fluent UI",
            role="Control plane, architecture inventory and operational status",
            durable=True,
            location="Hosted outside Oracle",
        ),
    ]
    return PlatformArchitecture(
        nodes=nodes,
        engineeringFlow=["contoso", "motherduck", "airflow", "spark", "motherduck", "bi"],
        mlEnrichmentFlow=["motherduck", "kaggle", "motherduck", "neon"],
        durableZones=[
            DurableDataZone(name="Raw", owner="MotherDuck / DuckLake", purpose="Generated Parquet and ingested source data"),
            DurableDataZone(name="Bronze", owner="MotherDuck / DuckLake", purpose="Durable landed / typed data"),
            DurableDataZone(name="Silver", owner="MotherDuck / DuckLake", purpose="Validated and conformed data"),
            DurableDataZone(name="Gold", owner="MotherDuck / DuckLake", purpose="Canonical analytical tables served outside the VM"),
            DurableDataZone(name="Features", owner="MotherDuck / DuckLake", purpose="ML-ready feature datasets derived from governed data"),
            DurableDataZone(name="ML results", owner="MotherDuck / DuckLake", purpose="Historical predictions and analytical model outputs"),
        ],
    )


def build_gold_catalog() -> list[GoldTableContract]:
    return [
        GoldTableContract(
            name="gold.sales_daily",
            grain="day × store × product",
            purpose="Business sales and margin analysis",
            consumers=["Power BI", "SQL"],
            storage="MotherDuck / DuckLake",
        ),
        GoldTableContract(
            name="gold.customer_360",
            grain="customer",
            purpose="Conformed customer profile and behavioral aggregates",
            consumers=["Power BI", "SQL", "ML features"],
            storage="MotherDuck / DuckLake",
        ),
        GoldTableContract(
            name="gold.delivery_performance",
            grain="shipment",
            purpose="Delivery reliability, delays and service-level analysis",
            consumers=["Power BI", "SQL", "ML features"],
            storage="MotherDuck / DuckLake",
        ),
        GoldTableContract(
            name="gold.customer_satisfaction",
            grain="customer × period",
            purpose="Reviews, support outcomes, returns and satisfaction KPIs",
            consumers=["Power BI", "SQL", "ML features"],
            storage="MotherDuck / DuckLake",
        ),
        GoldTableContract(
            name="gold.customer_scores",
            grain="customer × model version × scoring time",
            purpose="Historical model scores returned from the optional ML stage",
            consumers=["Power BI", "SQL"],
            storage="MotherDuck / DuckLake",
            mlDerived=True,
        ),
    ]
