from __future__ import annotations

from .models import (
    ContosoGenerationPlan,
    ContosoMlPlan,
    ContosoOutputPlan,
    ContosoScale,
    DataFactoryPlan,
    DataFactoryStage,
    DurableDataZone,
    GoldTableContract,
    PlatformArchitecture,
    PlatformNode,
    ProviderInventory,
    ProviderInventoryItem,
)


def build_platform_architecture() -> PlatformArchitecture:
    nodes = [
        PlatformNode(
            id="wind-source",
            name="FOIL WIND Synthetic Source",
            layer="source",
            state="planned",
            provider="Python / Polars",
            role="Deterministic synthetic WIND telemetry with explicit evidence classification",
            durable=False,
            location="Ephemeral Airflow task pod",
        ),
        PlatformNode(
            id="github",
            name="GitHub",
            layer="delivery",
            state="external",
            provider="GitHub",
            role="Source, DAGs, manifests, CI/CD and release artifacts",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="github-actions",
            name="GitHub Actions",
            layer="delivery",
            state="external",
            provider="GitHub",
            role="CI validation, ARM64 packaging and OpenTofu plan/apply workflow",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="cloudflare",
            name="Cloudflare",
            layer="delivery",
            state="external",
            provider="Cloudflare",
            role="Edge/DNS/access perimeter and frontend hosting target",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="motherduck",
            name="MotherDuck / DuckLake",
            layer="lakehouse",
            state="planned",
            provider="MotherDuck",
            role="Durable DuckLake analytical plane for Bronze, Silver, Gold and governed run history",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="oci-object-storage",
            name="OCI Object Storage",
            layer="lakehouse",
            state="planned",
            provider="Oracle Cloud",
            role="Immutable raw/archive Parquet and manifests for recovery",
            durable=True,
            location="Oracle Cloud managed storage",
        ),
        PlatformNode(
            id="fastapi-cloud",
            name="FastAPI Cloud",
            layer="control",
            state="external",
            provider="FastAPI Cloud",
            role="External ReactOracle Control API hosting target",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="oracle-agent",
            name="Oracle Ops Agent",
            layer="control",
            state="live",
            provider="Go / systemd",
            role="Outbound authenticated bridge for host and K3s telemetry/allow-listed operations",
            durable=False,
            location="Oracle host",
        ),
        PlatformNode(
            id="oracle-vm",
            name="Oracle A1 VM",
            layer="compute",
            state="live",
            provider="Oracle Cloud",
            role="K3s compute host for Airflow, Polars/DuckDB task pods and observability",
            durable=False,
            location="Oracle Cloud",
        ),
        PlatformNode(
            id="airflow",
            name="Airflow",
            layer="orchestration",
            state="planned",
            provider="Apache Airflow",
            role="Workflow orchestration using Kubernetes task execution on K3s",
            durable=False,
            location="Oracle K3s",
        ),
        PlatformNode(
            id="polars-duckdb",
            name="Polars + DuckDB",
            layer="compute",
            state="planned",
            provider="Python / DuckDB",
            role="Lightweight dataframe ETL and analytical SQL in ephemeral Airflow tasks",
            durable=False,
            location="Oracle K3s task pods",
        ),
        PlatformNode(
            id="neon",
            name="Neon",
            layer="serving",
            state="optional",
            provider="Neon Postgres",
            role="Compact run/result index and application-serving mirror of selected Gold outputs",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="fabric",
            name="Microsoft Fabric Lab",
            layer="consumption",
            state="external",
            provider="Microsoft Fabric",
            role="Separate real-time, Data Factory, OneLake and notebook lab; not Oracle storage",
            durable=True,
            location="External FOIL lab",
        ),
        PlatformNode(
            id="databricks",
            name="Databricks Lab",
            layer="ml",
            state="external",
            provider="Databricks",
            role="Separate frozen-snapshot Monte Carlo, PySpark, ML and MLflow experiments",
            durable=True,
            location="External FOIL lab",
        ),
        PlatformNode(
            id="bi",
            name="SQL / BI consumers",
            layer="consumption",
            state="planned",
            provider="SQL / BI",
            role="Consume governed Gold tables and compact serving outputs",
            durable=False,
            location="External clients",
        ),
        PlatformNode(
            id="grafana",
            name="Grafana stack",
            layer="observability",
            state="live",
            provider="Grafana / Prometheus / Loki",
            role="Operational metrics and logs",
            durable=False,
            location="Oracle K3s",
        ),
        PlatformNode(
            id="reactoracle",
            name="ReactOracle",
            layer="control",
            state="live",
            provider="React + Fluent UI",
            role="Control plane, architecture inventory and operational status",
            durable=True,
            location="Hosted outside Oracle",
        ),
    ]

    return PlatformArchitecture(
        nodes=nodes,
        deliveryFlow=["github", "github-actions", "cloudflare", "reactoracle"],
        controlFlow=["reactoracle", "fastapi-cloud", "oracle-agent", "oracle-vm"],
        engineeringFlow=["wind-source", "airflow", "polars-duckdb", "motherduck", "bi"],
        mlEnrichmentFlow=["motherduck", "databricks", "motherduck"],
        durableZones=[
            DurableDataZone(
                name="Raw archive",
                owner="OCI Object Storage",
                purpose="Immutable Parquet + manifest recovery copy (planned)",
            ),
            DurableDataZone(
                name="Bronze",
                owner="MotherDuck / DuckLake",
                purpose="Durable landed synthetic telemetry",
            ),
            DurableDataZone(
                name="Silver",
                owner="MotherDuck / DuckLake",
                purpose="Validated and conformed synthetic telemetry",
            ),
            DurableDataZone(
                name="Gold",
                owner="MotherDuck / DuckLake",
                purpose="Governed synthetic run summaries and analytical outputs",
            ),
            DurableDataZone(
                name="Features",
                owner="MotherDuck / DuckLake",
                purpose="Optional ML-ready datasets derived from governed data",
            ),
        ],
    )


def build_gold_catalog() -> list[GoldTableContract]:
    return [
        GoldTableContract(
            name="gold.wind_run_summary",
            grain="simulation run",
            purpose="Validated synthetic runtime summary with provenance and quality state",
            consumers=["ReactOracle", "SQL", "Neon serving mirror"],
            storage="MotherDuck / DuckLake",
        ),
        GoldTableContract(
            name="gold.wind_scenario_comparison",
            grain="scenario x machine revision",
            purpose="Compare governed synthetic WIND scenarios without promoting proxies to measured performance",
            consumers=["SQL", "notebooks", "Databricks frozen export"],
            storage="MotherDuck / DuckLake",
        ),
        GoldTableContract(
            name="gold.wind_quality_summary",
            grain="run x quality rule",
            purpose="Pipeline validation, anomaly counts and evidence-boundary checks",
            consumers=["ReactOracle", "Grafana", "SQL"],
            storage="MotherDuck / DuckLake",
        ),
    ]


def build_provider_inventory() -> ProviderInventory:
    return ProviderInventory(
        providers=[
            ProviderInventoryItem(
                id="oracle",
                name="Oracle Cloud",
                category="compute",
                state="live",
                role="ARM64 VM for K3s, Airflow, Polars/DuckDB task pods and observability",
                costIntent="free-tier",
                telemetry="partial",
                limitsVerified=False,
                detail="Host telemetry is live through the agent; pipeline deployment is not yet runtime-verified.",
            ),
            ProviderInventoryItem(
                id="github",
                name="GitHub",
                category="code",
                state="external",
                role="Source, DAGs, manifests, CI/CD and release artifacts",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="GitHub is the source-code authority for this implementation.",
            ),
            ProviderInventoryItem(
                id="motherduck",
                name="MotherDuck / DuckLake",
                category="lakehouse",
                state="planned",
                role="Durable Bronze/Silver/Gold analytical plane for the Oracle lab",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Code can target MotherDuck via DuckDB; live token/database verification remains pending.",
            ),
            ProviderInventoryItem(
                id="neon",
                name="Neon",
                category="database",
                state="optional",
                role="Compact run/result serving index and selected Gold mirror",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Not the canonical Bronze/Silver/Gold store.",
            ),
            ProviderInventoryItem(
                id="fabric",
                name="Microsoft Fabric",
                category="lab",
                state="external",
                role="Separate FOIL real-time/Data Factory/OneLake experiment platform",
                costIntent="unknown",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Kept outside the Oracle pipeline and governed by the Fabric lab.",
            ),
            ProviderInventoryItem(
                id="databricks",
                name="Databricks",
                category="lab",
                state="external",
                role="Frozen-snapshot Monte Carlo, PySpark, ML and MLflow lab",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Separate research execution path; not the Oracle medallion engine.",
            ),
            ProviderInventoryItem(
                id="cloudflare",
                name="Cloudflare",
                category="edge",
                state="external",
                role="Edge/DNS/access perimeter and frontend hosting target",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Portal/link integration only until a usage adapter exists.",
            ),
            ProviderInventoryItem(
                id="fastapi-cloud",
                name="FastAPI Cloud",
                category="api",
                state="external",
                role="External ReactOracle Control API hosting target",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Control-plane hosting remains outside the Oracle VM.",
            ),
        ]
    )


def build_data_factory_plan() -> DataFactoryPlan:
    source = ContosoGenerationPlan(
        scenario="foil.wind.synthetic_runtime",
        generator="FOIL WIND Synthetic Source",
        seed=20260922,
        optional=False,
        scale=ContosoScale(orders=300, customers=1, products=1, stores=1, days=1),
        ml=ContosoMlPlan(
            profile="synthetic-wind-proxy-v1",
            positiveOutcomeRate=0.0,
            signalStrength=0.0,
            noiseLevel=0.0,
            target="runtime quality and scenario summaries",
            primarySignal="wind speed + yaw alignment proxies",
            optional=True,
        ),
        output=ContosoOutputPlan(
            format="Parquet",
            destination="MotherDuck / DuckLake",
            durableZones=["Bronze", "Silver", "Gold"],
        ),
    )

    return DataFactoryPlan(
        contoso=source,
        coreStages=[
            DataFactoryStage(
                id="generate",
                name="Generate WIND telemetry",
                engine="Python / Polars",
                location="Airflow task pod",
                state="planned",
                detail="Deterministic SYNTHETIC telemetry + provenance manifest for MACHINE-WIND-001",
            ),
            DataFactoryStage(
                id="lake-raw",
                name="Archive Raw",
                engine="Parquet",
                location="OCI Object Storage",
                state="planned",
                detail="Immutable raw/recovery copy; separate from analytical medallion tables",
            ),
            DataFactoryStage(
                id="orchestrate",
                name="Orchestrate",
                engine="Airflow",
                location="Oracle K3s",
                state="planned",
                detail="DAG coordinates generation, Polars validation, DuckDB SQL and publication",
            ),
            DataFactoryStage(
                id="process",
                name="Process",
                engine="Polars + DuckDB",
                location="Oracle K3s task pods",
                state="planned",
                detail="Validate and transform SYNTHETIC telemetry into Bronze / Silver / Gold",
            ),
            DataFactoryStage(
                id="publish",
                name="Publish Gold",
                engine="DuckLake",
                location="MotherDuck",
                state="planned",
                detail="Canonical durable analytical tables in MotherDuck hosted DuckLake",
            ),
            DataFactoryStage(
                id="consume",
                name="Serve Gold",
                engine="SQL / API",
                location="External consumers",
                state="planned",
                detail="ReactOracle, SQL clients and optional Neon mirror consume compact Gold outputs",
            ),
        ],
        mlStages=[
            DataFactoryStage(
                id="features",
                name="Freeze research input",
                engine="DuckLake / Parquet",
                location="MotherDuck",
                state="planned",
                detail="Create explicit versioned/frozen dataset for research use",
            ),
            DataFactoryStage(
                id="train",
                name="Research / ML",
                engine="PySpark / MLflow",
                location="Databricks",
                state="external",
                detail="Separate FOIL research lab; never overwrites Core Truth",
            ),
            DataFactoryStage(
                id="publish-ml",
                name="Return approved summary",
                engine="DuckLake",
                location="MotherDuck",
                state="planned",
                detail="Only governed derived outputs return to the Oracle analytical plane",
            ),
            DataFactoryStage(
                id="serve-ml",
                name="Mirror compact results",
                engine="PostgreSQL",
                location="Optional Neon",
                state="optional",
                detail="Compact run/result serving state only",
            ),
        ],
        executionEnabled=False,
        businessReactInScope=False,
    )
