from __future__ import annotations

from .models import ContosoGenerationPlan, ContosoMlPlan, ContosoOutputPlan, ContosoScale, DataFactoryPlan, DataFactoryStage, DurableDataZone, GoldTableContract, PlatformArchitecture, PlatformNode, ProviderInventory, ProviderInventoryItem


def build_platform_architecture() -> PlatformArchitecture:
    nodes = [
        PlatformNode(
            id="contoso",
            name="Contoso Forge Lite",
            layer="source",
            state="planned",
            provider=".NET / C#",
            role="Optional deterministic synthetic retail data + causal ML truth",
            durable=False,
            location="Ephemeral generator job",
        ),
        PlatformNode(
            id="github",
            name="GitHub",
            layer="delivery",
            state="external",
            provider="GitHub",
            role="Source, DAGs, manifests, CI/CD and release artifacts",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="github-actions",
            name="GitHub Actions",
            layer="delivery",
            state="external",
            provider="GitHub",
            role="CI validation, ARM64 packaging and future OpenTofu plan/apply workflow",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="cloudflare",
            name="Cloudflare",
            layer="delivery",
            state="external",
            provider="Cloudflare",
            role="Edge/DNS/access perimeter and frontend hosting target",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="motherduck",
            name="MotherDuck / DuckLake",
            layer="lakehouse",
            state="planned",
            provider="MotherDuck",
            role="Durable Parquet lakehouse for Raw, Bronze, Silver, Gold and ML features",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="fastapi-cloud",
            name="FastAPI Cloud",
            layer="control",
            state="external",
            provider="FastAPI Cloud",
            role="External ReactOracle Control API hosting target",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="oracle-agent",
            name="Oracle Ops Agent",
            layer="control",
            state="live",
            provider="Go / systemd",
            role="Outbound authenticated bridge for host and K3s telemetry/allow-listed operations",
            durable=False,
            location="Oracle host",
        ),
        PlatformNode(
            id="oracle-vm",
            name="Oracle A1 VM",
            layer="compute",
            state="live",
            provider="Oracle Cloud",
            role="K3s compute host for Airflow, Spark and observability",
            durable=False,
            location="Oracle Cloud",
        ),
        PlatformNode(
            id="airflow",
            name="Airflow",
            layer="orchestration",
            state="live",
            provider="Apache Airflow",
            role="Pipeline orchestration and external job coordination",
            durable=False,
            location="Oracle K3s",
        ),
        PlatformNode(
            id="spark",
            name="Spark",
            layer="compute",
            state="live",
            provider="Apache Spark",
            role="Distributed transformations, joins, partitioning and feature engineering",
            durable=False,
            location="Oracle K3s",
        ),
        PlatformNode(
            id="kafka",
            name="Managed Kafka",
            layer="source",
            state="external",
            provider="External free tier",
            role="Streaming source without consuming Oracle VM memory",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="kaggle",
            name="Kaggle + MLJAR",
            layer="ml",
            state="planned",
            provider="Kaggle",
            role="Optional bounded external ML / AutoML execution from feature tables",
            durable=False,
            location="Managed external compute",
        ),
        PlatformNode(
            id="neon",
            name="Neon",
            layer="serving",
            state="optional",
            provider="Neon Postgres",
            role="Compact serving tables, ML metrics, latest predictions and platform metadata",
            durable=True,
            location="Managed external",
        ),
        PlatformNode(
            id="dbt",
            name="dbt",
            layer="serving",
            state="planned",
            provider="dbt Core",
            role="Optional analytical marts over durable Gold data",
            durable=False,
            location="Ephemeral Oracle K3s job",
        ),
        PlatformNode(
            id="bi",
            name="BI / SQL consumers",
            layer="consumption",
            state="planned",
            provider="Power BI / SQL",
            role="Consume published Gold tables; business React applications are out of scope",
            durable=False,
            location="External clients",
        ),
        PlatformNode(
            id="grafana",
            name="Grafana stack",
            layer="observability",
            state="live",
            provider="Grafana / Prometheus / Loki",
            role="Operational metrics and logs",
            durable=False,
            location="Oracle K3s",
        ),
        PlatformNode(
            id="reactoracle",
            name="ReactOracle",
            layer="control",
            state="live",
            provider="React + Fluent UI",
            role="Control plane, architecture inventory and operational status",
            durable=True,
            location="Hosted outside Oracle",
        ),
    ]
    return PlatformArchitecture(
        nodes=nodes,
        deliveryFlow=["github", "github-actions", "cloudflare", "reactoracle"],
        controlFlow=["reactoracle", "fastapi-cloud", "oracle-agent", "oracle-vm"],
        engineeringFlow=["contoso", "motherduck", "airflow", "spark", "motherduck", "bi"],
        mlEnrichmentFlow=["motherduck", "kaggle", "motherduck"],
        durableZones=[
            DurableDataZone(name="Raw", owner="MotherDuck / DuckLake", purpose="Generated Parquet and ingested source data"),
            DurableDataZone(name="Bronze", owner="MotherDuck / DuckLake", purpose="Durable landed / typed data"),
            DurableDataZone(name="Silver", owner="MotherDuck / DuckLake", purpose="Validated and conformed data"),
            DurableDataZone(name="Gold", owner="MotherDuck / DuckLake", purpose="Canonical analytical tables served outside the VM"),
            DurableDataZone(name="Features", owner="MotherDuck / DuckLake", purpose="ML-ready feature datasets derived from governed data"),
            DurableDataZone(name="ML results", owner="MotherDuck / DuckLake", purpose="Historical predictions and analytical model outputs"),
        ],
    )


def build_gold_catalog() -> list[GoldTableContract]:
    return [
        GoldTableContract(
            name="gold.sales_daily",
            grain="day × store × product",
            purpose="Business sales and margin analysis",
            consumers=["Power BI", "SQL"],
            storage="MotherDuck / DuckLake",
        ),
        GoldTableContract(
            name="gold.customer_360",
            grain="customer",
            purpose="Conformed customer profile and behavioral aggregates",
            consumers=["Power BI", "SQL", "ML features"],
            storage="MotherDuck / DuckLake",
        ),
        GoldTableContract(
            name="gold.delivery_performance",
            grain="shipment",
            purpose="Delivery reliability, delays and service-level analysis",
            consumers=["Power BI", "SQL", "ML features"],
            storage="MotherDuck / DuckLake",
        ),
        GoldTableContract(
            name="gold.customer_satisfaction",
            grain="customer × period",
            purpose="Reviews, support outcomes, returns and satisfaction KPIs",
            consumers=["Power BI", "SQL", "ML features"],
            storage="MotherDuck / DuckLake",
        ),
        GoldTableContract(
            name="gold.customer_scores",
            grain="customer × model version × scoring time",
            purpose="Historical model scores returned from the optional ML stage",
            consumers=["Power BI", "SQL"],
            storage="MotherDuck / DuckLake",
            mlDerived=True,
        ),
    ]



def build_provider_inventory() -> ProviderInventory:
    # Cost intent describes the lab target, not a verified provider entitlement.
    # Exact free-tier limits are intentionally omitted until a provider adapter verifies them.
    return ProviderInventory(
        providers=[
            ProviderInventoryItem(
                id="oracle",
                name="Oracle Cloud",
                category="compute",
                state="live",
                role="ARM64 VM running K3s, Airflow, Spark and observability",
                costIntent="free-tier",
                telemetry="partial",
                limitsVerified=False,
                detail="Host telemetry is live through the agent; billing/free-tier quota API is not connected.",
            ),
            ProviderInventoryItem(
                id="github",
                name="GitHub",
                category="code",
                state="external",
                role="Source repositories, DAGs, manifests, CI/CD and release artifacts",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="GitHub is the active source/CI provider, but ReactOracle has no GitHub usage adapter connected yet.",
            ),
            ProviderInventoryItem(
                id="cloudflare",
                name="Cloudflare",
                category="edge",
                state="external",
                role="DNS, access perimeter and potential ReactOracle frontend hosting",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Portal/link integration only until an explicit usage adapter is added.",
            ),
            ProviderInventoryItem(
                id="fastapi-cloud",
                name="FastAPI Cloud",
                category="api",
                state="external",
                role="External ReactOracle Control API hosting target",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Control-plane hosting is external to the Oracle VM.",
            ),
            ProviderInventoryItem(
                id="motherduck",
                name="MotherDuck / DuckLake",
                category="lakehouse",
                state="planned",
                role="Durable Raw, Bronze, Silver, Gold, Features and ML history",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Canonical durable analytical plane; provider adapter is a later slice.",
            ),
            ProviderInventoryItem(
                id="kafka",
                name="Managed Kafka",
                category="streaming",
                state="planned",
                role="External streaming source without JVM pressure on Oracle",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Provider remains configurable; do not hard-code a vendor or mutable quota.",
            ),
            ProviderInventoryItem(
                id="kaggle",
                name="Kaggle",
                category="ml",
                state="planned",
                role="Optional MLJAR / ML execution from governed feature datasets",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Execution/result adapter is planned; ML is not required for serving Gold.",
            ),
            ProviderInventoryItem(
                id="neon",
                name="Neon",
                category="database",
                state="optional",
                role="Compact serving state, ML metadata and PostgreSQL exercises",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Not the canonical Gold store.",
            ),
            ProviderInventoryItem(
                id="colab",
                name="Google Colab",
                category="lab",
                state="optional",
                role="Disposable interactive Python / ML notebook lab",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Never a core Spark cluster or persistent runtime dependency.",
            ),
            ProviderInventoryItem(
                id="huggingface",
                name="Hugging Face",
                category="artifacts",
                state="optional",
                role="Potential model/dataset artifact publication",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Optional artifact ecosystem, not core compute.",
            ),
            ProviderInventoryItem(
                id="gitlab",
                name="GitLab",
                category="cicd",
                state="optional",
                role="Optional secondary CI/CD lab",
                costIntent="free-tier",
                telemetry="not-connected",
                limitsVerified=False,
                detail="Not required while GitHub Actions remains the active delivery path.",
            ),
        ]
    )



def build_data_factory_plan() -> DataFactoryPlan:
    contoso = ContosoGenerationPlan(
        scenario="retail.customer_satisfaction",
        generator="Contoso Forge Lite",
        seed=20260904,
        optional=True,
        scale=ContosoScale(orders=1200, customers=240, products=48, stores=4, days=365),
        ml=ContosoMlPlan(
            profile="causal-v1",
            positiveOutcomeRate=0.1,
            signalStrength=0.5,
            noiseLevel=0.1,
            target="customer dissatisfaction",
            primarySignal="delivery delay",
            optional=True,
        ),
        output=ContosoOutputPlan(
            format="Parquet",
            destination="MotherDuck / DuckLake",
            durableZones=["Raw", "Bronze", "Silver", "Gold", "Features"],
        ),
    )
    return DataFactoryPlan(
        contoso=contoso,
        coreStages=[
            DataFactoryStage(id="generate", name="Generate", engine=".NET / C#", location="Contoso Forge Lite", state="planned", detail="Optional deterministic retail source + truth manifest"),
            DataFactoryStage(id="lake-raw", name="Land Raw", engine="Parquet / DuckLake", location="MotherDuck", state="planned", detail="Durable generated source outside the Oracle VM"),
            DataFactoryStage(id="orchestrate", name="Orchestrate", engine="Airflow", location="Oracle K3s", state="live", detail="DAG coordinates ingestion and Spark stages"),
            DataFactoryStage(id="process", name="Process", engine="Spark", location="Oracle K3s", state="live", detail="Bronze / Silver / Gold / feature engineering"),
            DataFactoryStage(id="publish", name="Publish Gold", engine="DuckLake", location="MotherDuck", state="planned", detail="Canonical durable analytical tables"),
            DataFactoryStage(id="consume", name="Serve Gold", engine="SQL / BI", location="External consumers", state="planned", detail="Power BI, SQL clients, notebooks and APIs consume Gold"),
        ],
        mlStages=[
            DataFactoryStage(id="features", name="Read Features", engine="DuckLake", location="MotherDuck", state="planned", detail="Governed ML feature dataset derived from durable analytical data"),
            DataFactoryStage(id="train", name="Train", engine="MLJAR", location="Kaggle", state="planned", detail="Optional bounded external AutoML experiment"),
            DataFactoryStage(id="publish-ml", name="Publish ML results", engine="DuckLake", location="MotherDuck", state="planned", detail="Historical predictions and analytical results return to durable storage"),
            DataFactoryStage(id="serve-ml", name="Mirror latest state", engine="PostgreSQL", location="Optional Neon", state="optional", detail="Compact latest predictions / metrics only when a serving use case needs them"),
        ],
        executionEnabled=False,
        businessReactInScope=False,
    )
